version: '3.4'

services:
  sliverdocs:
    image: sliverdocs
    build:
      context: docs/sliver-docs
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
